#define SRELL_NO_THROW 1
#define LUA_USE_LONGJMP

#include "../Code/MainSDL2.cpp"
#include "../Code/ttf_roboto.cpp"
#include "../Code/ttf_noto.cpp"
#include "../Code/Styles.cpp"
#include "../Code/Renderer.cpp"
#include "../Code/stb_truetype.cpp"
#include "../Code/PlatformWasm.cpp"
#include "../Code/IncludedDocuments.cpp"
#include "../Code/Font.cpp"
#include "../Code/FileMenu.cpp"
#include "../Code/DocumentView.cpp"
#include "../Code/DocumentContainer.cpp"
#include "../Code/Document.cpp"
#include "../Code/application.cpp"
extern "C" {
    #include "../Code/miniz.c"

    #undef tonumber
    #undef tointeger

    #include "../Code/lua/lua.h"
    #include "../Code/lua/lualib.h"
    #include "../Code/lua/lauxlib.h"
    #include "../Code/lua/luaconf.h"

    #include "../Code/lua/lapi.c"
    #include "../Code/lua/lauxlib.c"
    #include "../Code/lua/lbaselib.c"
    #include "../Code/lua/lcode.c"
    #include "../Code/lua/lcorolib.c"
    #include "../Code/lua/lctype.c"
    #include "../Code/lua/ldblib.c"
    #include "../Code/lua/ldebug.c"
    #include "../Code/lua/ldo.c"
    #include "../Code/lua/ldump.c"
    #include "../Code/lua/lfunc.c"
    #include "../Code/lua/lgc.c"
    #include "../Code/lua/linit.c"
    #include "../Code/lua/liolib.c"
    #include "../Code/lua/llex.c"
    #include "../Code/lua/lmathlib.c"
    #include "../Code/lua/lmem.c"
    #include "../Code/lua/loadlib.c"
    #include "../Code/lua/lobject.c"
    #include "../Code/lua/lopcodes.c"
    #include "../Code/lua/loslib.c"
    #include "../Code/lua/lparser.c"
    #include "../Code/lua/lstate.c"
    #include "../Code/lua/lstring.c"
    #include "../Code/lua/lstrlib.c"
    #include "../Code/lua/ltable.c"
    #include "../Code/lua/ltablib.c"
    #include "../Code/lua/ltm.c"
    #include "../Code/lua/lua.hpp"
    #include "../Code/lua/lundump.c"
    #include "../Code/lua/lutf8lib.c"
    #include "../Code/lua/lvm.c"
    #include "../Code/lua/lzio.c"
}

#include "../Code/ScriptingInterface.cpp"
